### This notebook shows how to perform the following data transformations to prepare the data for data visualizations or further analysis:   
- Get first row to be column headers
- Replace na with missing values
- Transpose columns to rows (change from wide to long format) 

### The dataset used is on Graduates From University First Degree Courses By Type Of Course And Sex in Singapore from [SingStat](https://tablebuilder.singstat.gov.sg/table/TS/M850511) and made available on datadoubleconfirm github repo [here](https://github.com/hxchua/datadoubleconfirm/blob/master/datasets/unigradsg.csv) in the format below.

In [1]:
import numpy as np

In [2]:
import pandas as pd
url = 'https://raw.githubusercontent.com/hxchua/datadoubleconfirm/refs/heads/master/datasets/unigradsg.csv'
df = pd.read_csv(url)

In [3]:
df

,new_column_0,new_column_1,new_column_2,new_column_3,new_column_4,new_column_5,new_column_6,new_column_7,new_column_8,new_column_9,...,new_column_22,new_column_23,new_column_24,new_column_25,new_column_26,new_column_27,new_column_28,new_column_29,new_column_30,new_column_31
0,Data Series,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,2002,2001,2000,1999,1998,1997,1996,1995,1994,1993
1,Males,10516,10491,10058,9880,9429,9404,8963,7703,7872,...,4858,4735,4536,4573,4455,4276,4022,4003,3889,3565
2,Males: Education,64,62,46,58,54,73,65,79,99,...,63,63,35,44,56,45,46,12,na,na
3,Males: Applied Arts,149,135,180,163,186,189,175,173,187,...,na,na,na,na,na,na,na,na,na,na
4,Males: Humanities & Social Sciences,1480,1160,1192,1180,1119,1095,1078,803,743,...,591,534,574,576,547,554,497,497,512,481
5,Males: Mass Communication & Information Science,56,86,92,82,74,68,78,35,42,...,30,39,34,19,27,28,na,na,na,na
6,Males: Accountancy,552,574,638,625,611,596,574,439,480,...,226,257,250,297,264,227,262,289,271,295
7,Males: Business & Administration,1449,1408,1284,1121,1076,1082,973,751,771,...,318,403,328,349,461,448,358,365,413,282
8,Males: Law,238,231,199,190,217,238,187,178,187,...,73,58,74,92,70,90,75,94,87,92
9,Males: Natural & Mathematical Sciences,354,784,761,816,812,849,743,755,790,...,276,358,378,401,422,437,449,460,374,404
10,Males: Medicine,231,229,201,208,194,166,145,131,137,...,122,97,119,104,106,107,97,93,99,95
11,Males: Dentistry,21,26,25,16,19,14,23,25,19,...,23,19,17,18,24,20,24,20,23,14
12,Males: Health Sciences,257,244,209,211,154,150,142,112,128,...,20,17,11,14,8,9,9,12,14,10
13,Males: Information Technology,1826,1364,1100,1068,884,954,758,670,689,...,365,249,348,355,377,370,362,306,294,264
14,"Males: Architecture, Building & Real Estate",276,281,302,254,285,271,273,185,188,...,134,124,101,104,141,135,142,140,136,132
15,Males: Engineering Sciences,3374,3742,3657,3717,3605,3514,3593,3283,3258,...,2617,2517,2267,2200,1952,1806,1701,1715,1666,1496
16,Males: Services,163,145,158,158,129,128,145,84,154,...,na,na,na,na,na,na,na,na,na,na
17,Females,11117,10316,9685,9938,9744,9593,9574,8192,7638,...,5354,5124,4870,4890,4876,4403,4196,3923,3625,3683
18,Females: Education,265,284,289,271,254,358,328,341,317,...,163,147,115,158,133,187,199,101,na,na
19,Females: Applied Arts,221,200,269,281,263,293,276,259,233,...,na,na,na,na,na,na,na,na,na,na
20,Females: Humanities & Social Sciences,2939,2511,2310,2477,2438,2369,2353,1760,1450,...,1609,1520,1452,1492,1547,1367,1364,1240,1133,1173
21,Females: Mass Communication & Information Sc...,219,213,189,197,222,196,192,153,130,...,91,77,80,93,74,67,na,na,na,na
22,Females: Accountancy,774,659,757,843,864,752,752,664,556,...,541,484,495,482,487,453,433,395,378,396
23,Females: Business & Administration,2147,1900,1649,1472,1437,1291,1242,969,848,...,751,807,851,905,869,808,848,788,733,708
24,Females: Law,209,203,216,204,155,165,188,173,168,...,77,96,79,77,103,97,106,100,99,93
25,Females: Natural & Mathematical Sciences,544,863,884,1133,1212,1285,1337,1195,1145,...,699,754,655,674,678,600,541,572,566,588
26,Females: Medicine,210,192,196,178,181,189,156,147,115,...,60,42,37,41,42,40,53,48,66,61
27,Females: Dentistry,38,34,33,35,33,39,33,28,32,...,11,16,15,14,12,10,13,8,6,11
28,Females: Health Sciences,801,668,590,547,430,385,410,368,353,...,49,46,30,77,69,60,59,46,39,40
29,Females: Information Technology,917,608,464,440,408,393,367,381,377,...,199,133,187,218,296,218,194,193,196,215
30,"Females: Architecture, Building & Real Estate",347,365,313,318,369,398,303,274,351,...,224,199,192,167,153,163,136,156,182,144
31,Females: Engineering Sciences,1332,1505,1358,1405,1363,1346,1478,1385,1375,...,880,803,682,492,413,333,250,276,227,254
32,Females: Services,120,95,142,125,91,108,124,95,188,...,na,na,na,na,na,na,na,na,na,na

In [4]:
#get first row to be column headers
column_names = df.iloc[0].tolist()
df.columns = column_names
#remove first row
df = df[1:]
#replace na with missing values
df.replace("na", np.nan, inplace=True)
#transpose columns to rows
df = df.melt(id_vars=["Data Series"],
        var_name="Year",
        value_name="Value")

/tmp/ipykernel_3082921/4032711812.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace("na", np.nan, inplace=True)

In [5]:
df

                                           Data Series  Year  Value
0                                                Males  2023  10516
1                                     Males: Education  2023     64
2                                  Males: Applied Arts  2023    149
3                  Males: Humanities & Social Sciences  2023   1480
4      Males: Mass Communication & Information Science  2023     56
..                                                 ...   ...    ...
987                           Females: Health Sciences  1993     40
988                    Females: Information Technology  1993    215
989      Females: Architecture, Building & Real Estate  1993    144
990                      Females: Engineering Sciences  1993    254
991                                  Females: Services  1993    NaN

[992 rows x 3 columns]